package dk.kb.api.impl;

import dk.kb.api.*;
import dk.kb.api.model.Error;
import java.io.File;
import dk.kb.api.model.HelloReply;
import dk.kb.api.model.IdMetaPairs;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.model.wadl.Description;
import org.apache.cxf.jaxrs.model.wadl.DocTarget;

import org.apache.cxf.jaxrs.ext.multipart.*;


/**
 * KB API
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class DefaultApiServiceImpl implements DefaultApi {
    /**
     * Request a Hello World message, for testing purposes
     *
     */
    @Override
    public HelloReply getGreeting(String alternateHello) {
        HelloReply hello = new HelloReply();
        hello.setMessage("Hello " + (alternateHello == null ? "World" : alternateHello));
        return hello;
    }
    
    /**
     * Request meta data available at the Royal Danish Library
     *
     */
    @Override
    public List<IdMetaPairs> getMetaData(List<String> ids, String format) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Request a resource available at the Royal Danish Library
     *
     */
    @Override
    public File getResource(String id) {
        // TODO: Implement...
        
        return null;
    }
    
}

